### PR TITLE
Bump to aiobotocore 2.9.1

### PR DESCRIPTION
**Pull request by takeshitakenji**
Just bumped aiobotocore to 2.9.1.

### CODE REVIEW

**Comment by takeshitakenji** [comment]
@terrycain: Mind reviewing this when you get a chance?

**Comment by takeshitakenji** [comment]
@terrycain: Have you seen this PR?

**Comment by terrycain** [comment]
Sorry, have been away on business, will have a look at this in a bit

**Comment by terrycain** [comment]
Have released v12.3.0 which uses aiobotocore 2.11.2

**Pull request closed without merging**
