### PR TITLE
Update setup.py to be in sync with aiobotocore

### PR DESCRIPTION
**Pull request by opkorz**
Just wanted to update this because it actually downgrades the boto3 and botocore versions.

These are the current versions of boto3 and botocore:
```
boto3-1.14.60
botocore-1.17.60
```

### CODE REVIEW

**Comment by adamantike** [comment]
@opkorz, could you bump it further to `1.1.2`, considering it was [released a few days ago](https://github.com/aio-libs/aiobotocore/releases/tag/1.1.2)?

@terrycain, any chance to review this? The current dependency forces us to downgrade to boto3 1.12. With this change, we would still need to downgrade from 1.15 to 1.14, but it's a lot better (until `aiobotocore` gets the newer version, at least).

**Comment by ScriptAutomate** [comment]
@opkorz This PR is failing because you also need to update the `Pipfile` to reflect the update to `aiobotocore`. As @adamantike said, too, we should bump it once more to `1.1.2`.

@terrycain Doing so would also allow for the ability to close #208 also, since that was an attempted GitHub Actions PR to update the dependency previously in an automated fashion (but is now out of date).

**Comment by opkorz** [comment]
Hi @ScriptAutomate , @adamantike , thanks for pointing that out. I have just updated it to 1.1.2

**Comment by ScriptAutomate** [comment]
I'm stumped on the testing failures as I don't understand what the `test_patches.py` is meant to be doing. @terrycain can you help out on this?

```
...
tests/test_patches.py Boto3 version: 1.14.44 aiobotocore version: 1.1.2
Digest of ServiceAction.__call__:3e84efcb2badef725b998e1af27a4a6f6f1aa2ed not found in: {'79fa2006689fd33853f5c446e0a754a5a29e8ba9'}
Digest of BatchAction.__call__:8839f17467d16f98e4587fa750d74c9007dea134 not found in: {'fe7e5f191bf14db7c964e1165ce4c396b908a8db'}
Digest of Session.resource:5e3568b28281a75eaf9725fab67c33dc16a18144 not found in: {'873b7f61eaec2658925c58acaee80eec20eb5983'}
F
tests/test_s3.py ...........
tests/test_s3_cse.py x...............
=================================== FAILURES ===================================
_________________________________ test_patches _________________________________
...
...
```

Related to:

https://github.com/terrycain/aioboto3/blob/c23639e100959ed020151c73123885fbe8122067/tests/test_patches.py#L28-L29

https://github.com/terrycain/aioboto3/blob/c23639e100959ed020151c73123885fbe8122067/tests/test_patches.py#L54

It seems you are looking for the presence of some kind of "API digest" patch? This attempted update automatically fails the `tests/test_patches.py` because of the above calls, regardless of Python version being tested against.

**Comment by terrycain** [comment]
Hey, sorry was easier for me to bump the version than add to the pr. Thanks for waiting so long guys, haven't given this project the care it needs lately.

**Comment by terrycain** [comment]
8.1.0 is out :)

**Pull request closed without merging**
