### PR TITLE
Fix for #192 - support aiobotocore 0.12

### PR DESCRIPTION
**Pull request by snstanton**
- Update requirements to aiobotocore 0.12 or later.
- remove use of loop argument
- fix a few flake8 warnings
- require python 3.6 or later
- support python 3.8
- eliminate @async_generator uses
- bump version to 6.6.0

Note that this PR abandons support for python3.5 in favor of adding python3.8 support since 3.5 is no longer getting anything but security fixes.

### CODE REVIEW

**Comment by terrycain** [comment]
Nice work :smile: 

Can you update the .travis yaml to remove 3.5 and add 3.8 as I'll assume that's what broke the tests.
Also as we're dropping 3.5 wouldn't it make more sense to bump the version number to 7

**Comment by flavioribeiro** [comment]
@terrycain thinking of merging this one anytime soon?

**Comment by terrycain** [comment]
v7.0.0 should appear in pypi sometime today

**Comment by terrycain** [comment]
v7.0.0 out :smile:

**Comment by flavioribeiro** [comment]
cheers, thanks!!

**Comment by terrycain** [comment]
np

**Pull request merged**
