### PR TITLE
bump aiobotocore to 2.1.0 and aioboto3 to 9.3.1 versions

### PR DESCRIPTION
**Pull request by abivolmv**
bump aiobotocore to 2.1.0 and aioboto3 to 9.3.1 versions

### CODE REVIEW

**Comment by abivolmv** [comment]
@terrycain how would I run tests against buckets ? Is there a way to configure AWS Profile that should be used for tests ? I saw that in the tests it is generating bucket names based on uuid - so I suppose it is creating the bucket then deleting it ?

**Comment by terrycain** [comment]
Hey, so the tests spawn a mock s3 server (from the moto project) and uses that

**Comment by terrycain** [comment]
FYI the pyproject.toml version is ignored as the poetry-dynamic-versioning mentioned in the build_system section gets the version from a tag

**Comment by terrycain** [comment]
Tests look good :) thanks for this.

**Comment by terrycain** [comment]
v9.3.1 is on pypi :)

**Comment by abivolmv** [comment]
Ah ok, that's why it took a lot of time - I thought it's trying to create real buckets in aws.

**Comment by terrycain** [comment]
Nah it spins up a test server locally and uses that. It used to make buckets on aws but every now and again I'd debug tests and then kill them mid run and my aws account was being filled with random buckets

**Pull request merged**
