### PR TITLE
Bumped aiobotocore to 2.5.1

### PR DESCRIPTION
**Pull request by szymon-planeta**
bump to aiobotocore 2.5.1

### CODE REVIEW

**Comment by szymon-planeta** [comment]
@terrycain reviewed what causes the test to fail - aiobotocore update bumps boto3 from 1.26.76 to 1.26.161 which updates `upload_file` function code (from [this](https://github.com/boto/boto3/blob/46e333480221abb6973cb62498ca9bc93c203994/boto3/s3/inject.py#L105) to [this](https://github.com/boto/boto3/blob/4b03b73ba84fd3c088215357849defd8409bb255/boto3/s3/inject.py#L105)

Diff:
```
9,10c9,10
<         s3 = boto3.resource('s3')
<         s3.meta.client.upload_file('/tmp/hello.txt', 'mybucket', 'hello.txt')
---
>         s3 = boto3.client('s3')
>         s3.upload_file('/tmp/hello.txt', 'mybucket', 'hello.txt')
12,13c12,13
<     Similar behavior as S3Transfer's upload_file() method,
<     except that parameters are capitalized. Detailed examples can be found at
---
>     Similar behavior as S3Transfer's upload_file() method, except that
>     argument names are capitalized. Detailed examples can be found at
```

Since this changes only docstring I've assumed that it's safe to add new digest

**Comment by szymon-planeta** [comment]
@terrycain could you please take a look at this when you have a chance?
Would really like to use FaceOccluded which was added to Rekognition recently

**Comment by szymon-planeta** [comment]
@terrycain sorry for another bump, thought you might've missed it

**Comment by WilkenSteiner** [comment]
Hey @terrycain! It would be great to merge this, we need a patch that is included in a dependency of the more recent `aiobotocore`.

Hey @szymon-planeta ! May I add a commit bumping this directly to `2.5.4`? I lock to `boto3 = ["boto3 (>=1.28.17,<1.28.18)"]`, and your comment [still](https://github.com/boto/boto3/blob/1.28.17/boto3/s3/inject.py#L105) applies (and the hash you added doesn't change).

**Comment by szymon-planeta** [comment]
@WilkenSteiner sure

**Comment by terrycain** [comment]
Sorry for the absence guys. I'll be bumping to aiobotocore 2.6.0 today 😄 (i'll close this PR as it'll be superseded by my changes)

**Comment by terrycain** [comment]
v11.3.0 is out supporting aiobotocore 2.6.0

**Pull request closed without merging**
